// Generated by CoffeeScript 1.3.1
/* 
  Blogo v0.0.1
  Fetch and display RSS feeds
*/

(function($) {
  return $.fn.blogo = function(options) {
    var default_options, googleFeed, opts;
    if (options == null) {
      options = {};
    }
    googleFeed = 'https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&callback=?';
    default_options = {
      layout: '<h3><a href="ENTRY_URL" target="_blank">ENTRY_TITLE</a></h3><p>ENTRY_SNIPPET <a href="ENTRY_URL" target="_blank">Read More</a></p>',
      numPosts: 3
    };
    opts = $.extend({}, default_options, options);
    return this.each(function() {
      var that;
      that = this;
      return $.getJSON(googleFeed, {
        q: opts.feed,
        num: opts.numPosts
      }, function(data, textStatus, jqXHR) {
        var result;
        result = [];
        $.each(data.responseData.feed.entries, function(i, entry) {
          return result.push(opts.layout.replace(/ENTRY_TITLE/g, entry.title).replace(/ENTRY_SNIPPET/g, entry.contentSnippet).replace(/ENTRY_URL/g, entry.link));
        });
        console.log(result, $(that));
        return $(that).append(result.join(''));
      });
    });
  };
})(jQuery);
